spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pizzahouse?useSSL=false
    username: root
    password: bpk@root

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER



#JPA Settings
  jpa.hibernate.ddl_auto: create